---
- name: Initiate master node
  command: >
    kubeadm init
    --pod-network-cidr 10.244.0.0/16
    --apiserver-advertise-address {{ apiserver_advertise_address }}
  args:
    creates: /etc/kubernetes/admin.conf

# - name: Install Flannel network plugin
#   k8s:
#     kubeconfig: /etc/kubernetes/admin.conf
#     src: https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml
- name: Create admission token
  command: kubeadm token create
  register: kubeadm_token_create

- name: Save admission token as fact
  set_fact:
    admission_token: "{{ kubeadm_token_create.stdout }}"

# Considered non-idempotent by Ansible
# TODO: Make Ansible understand that it is idempotent.
- name: Install Flannel network plugin
  command: >
    kubectl apply
    --kubeconfig /etc/kubernetes/admin.conf
    --filename https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml
